# Clase 1 - Semana 5
#### Tópicos Selectos Proceso Químicos: Análisis de Datos con Python

# Funciones

Una función es un conjunto de instrucciones que se agrupan para realizar una tarea específica.

- Recibe datos (entrada), los procesa y devuelve un resultado (salida).

*Sirven para reutilizar código, organizar mejor los programas y evitar repetir instrucciones.*


| Concepto       | Significado                             |
| -------------- | --------------------------------------- |
| **def**        | palabra clave para definir una función  |
| **Parámetros** | datos que la función recibe             |
| **return**     | indica qué valor devuelve la función    |
| **Llamada**    | cuando usamos la función en el programa |


In [ ]:
def sumar(a, b):  #La función recibe dos números, realiza una operación y devuelve el resultado.
    resultado = a + b
    return resultado

In [ ]:
sumar(4324,234) #Llamar la función suma

4558

In [ ]:
def resta(a,b):
    res = a - b
    return res

In [ ]:
resta(19, 27)

-8

Crear una función que convierta temperatura Celsius a Kelvin:

In [ ]:
def conversionC_K(T_C):
    res= T_C + 273.15
    return res

In [ ]:
conversionC_K(25)

298.15

Crear un afunción para convertir de bar a MPa

In [ ]:
def bar_MP(P_bar):
    res=P_bar * 0.1
    return res

In [ ]:
bar_MP(10)

1.0

# Uso de funciones para evaluar el estado termodinámico del agua

Realizar un  código que acepte temperatura y presión en distintas unidades y determine el estado del agua.

| Condición           | Estado del agua          |
| ------------------- | ------------------------ |
| T < Tc y P < Pc     | Líquido o vapor          |
| T > Tc y P > Pc     | Supercrítico             |
| T < Tc y P > Pc     | Líquido comprimido       |
| Otras combinaciones | Cercano al punto crítico |


Paso 1: Funciones de conversión de Temperatura y presión

> Función que cambie de:
- C a K
- F a K
- R a K



In [ ]:

def a_K(T, unidad):
    if unidad == "C":
       res= T +273.15
       return res
    elif unidad == "F":
      res = (T - 32)* 5/9 +273.15
      return res
    elif unidad == "R":
       res = T* 5/9
       return res
    else:
      print("Dato no válido, verifique las unidades")


In [ ]:
a_K(25, "F")

269.26111111111106

In [ ]:
a_K(25, "h")

Dato no válido, verifique las unidades


> Crear una función que cambie unidades de presión

- bar MPa

- mmHg MPa

- Psi  MPa


In [ ]:
def p_MPa(P, unidad):
    if unidad == "bar":
       res= P*0.1
       return res
    elif unidad == "mmHg":
      res = P / 7501
      return res
    elif unidad == "Psi":
       res = P / 145
       return res
    else:
      print("Dato no válido, verifique las unidades")

In [ ]:
p_MPa(10, "Psi")

0.06896551724137931

Ahora añadimos más temperaturas

In [ ]:
def T_kelvin(T, unidad):
    if unidad == "C":
        return T + 273.15
    elif unidad == "F":
        return (T - 32)* 5/9 + 273.15
    elif unidad == "R":
        return T* 5/9
    elif unidad == "K":
        return T
    else:
       raise ValueError("Unidad de temperatura no válida. Usa C, F, R o K.")



In [ ]:
print(T_kelvin(25, "R"))


13.88888888888889


Conversiones P

In [ ]:
def P_MPa(P, unidad):
    if unidad == "bar":
        return P * 0.1
    elif unidad == "mmHg":
        return P/7501
    elif unidad == "Psi":
        return P / 145
    elif unidad == "atm":
        return P * 0.101325
    elif unidad == "MPa":
        return P
    else:
       raise ValueError("Unidad de Presión no válida. Usa bar, mmHg, Psi, atm o MPa")


In [ ]:
print(P_MPa(10, "mmHg"))

0.0013331555792560992


In [ ]:
def clasificar_estado(T_K, P_MPa):
    Tc = 647.1
    Pc = 22.06

    if T_K < Tc and P_MPa < Pc:
        return "Líquido o vapor"
    elif T_K > Tc and P_MPa > Pc:
        return "Supercrítico"
    elif T_K < Tc and P_MPa > Pc:
        return "Líquido comprimido"
    else:
        return "Cerca del punto crítico"


In [ ]:
T = float(input("Temperatura: "))
uT = input("Unidad (C, F, R o K): ")

P = float(input("Presión: "))
uP = input("Unidad (bar, mmHg, Psi, atm o MPa): ")

T_K = T_kelvin(T, uT)
P_MPa = P_mpa(P, uP)

print(clasificar_estado(T_K, P_MPa))


Temperatura: 25
Unidad (C, F, R o K): R
Presión: 2
Unidad (bar, mmHg, Psi, atm o MPa): atm
Líquido o vapor


# Expresión Regular



In [ ]:
capitales = ['#Ciudad Victo*ria', 'cuerna#vaca', 'Morelia!', 'xalapa', 'Tepic', 'hermos*illo',
 'toluca?', 'San? Luis Potosí', '*Mexicali', 'Villahermosa', 'Tuxtla Gutiérrez#',
 'Colima', 'la Paz#', 'Guadalajara', 'C*ampeche!', 'Durango', 'Zacatecas',
 '!Chetumal', 'Ciudad# de México', 'chilpancingo*', 'Chihua#hua', '?Aguascalientes',
 'Oaxaca de Juárez*', '?Puebla', 'Quer?étaro', 'Mérida', 'guanajuato',
 'pachu*ca', '#Saltillo#', 'Culiacán!', 'Tlaxcala', 'monterrey']


Una expresión regular (o regex, por regular expression) es una secuencia de caracteres que define un patrón de búsqueda en cadenas de texto. Se usa para buscar, validar, reemplazar o dividir texto de forma eficiente y flexible.

Una forma de limpiar la lista es utilizando métodos de cadena de texto internos junto con el módulo de librería estándar **re** para las expresiones regulares:

In [ ]:
import re

def limpiar_cadenas(strings):
    result = []
    for value in strings:
        value = value.strip()  # suprime blancos u otro carácter especificado del final o del principio de una expresión
        value = re.sub('[#*?!]', '', value) #reemplaza todas las ocurrencias de un patrón por el texto que especifiquemos
        value = value.title() #convierte la primera letra de cada palabra de una cadena a mayúsculas.
        result.append(value)
    return result

In [ ]:
limpiar_cadenas(capitales)

['Ciudad Victoria',
 'Cuernavaca',
 'Morelia',
 'Xalapa',
 'Tepic',
 'Hermosillo',
 'Toluca',
 'San Luis Potosí',
 'Mexicali',
 'Villahermosa',
 'Tuxtla Gutiérrez',
 'Colima',
 'La Paz',
 'Guadalajara',
 'Campeche',
 'Durango',
 'Zacatecas',
 'Chetumal',
 'Ciudad De México',
 'Chilpancingo',
 'Chihuahua',
 'Aguascalientes',
 'Oaxaca De Juárez',
 'Puebla',
 'Querétaro',
 'Mérida',
 'Guanajuato',
 'Pachuca',
 'Saltillo',
 'Culiacán',
 'Tlaxcala',
 'Monterrey']

In [ ]:
capitales_limpias = limpiar_cadenas(capitales)

capitales_limpias.sort() #sort para ordenar en orden Alfabético

In [ ]:
capitales_limpias

['Aguascalientes',
 'Campeche',
 'Chetumal',
 'Chihuahua',
 'Chilpancingo',
 'Ciudad De México',
 'Ciudad Victoria',
 'Colima',
 'Cuernavaca',
 'Culiacán',
 'Durango',
 'Guadalajara',
 'Guanajuato',
 'Hermosillo',
 'La Paz',
 'Mexicali',
 'Monterrey',
 'Morelia',
 'Mérida',
 'Oaxaca De Juárez',
 'Pachuca',
 'Puebla',
 'Querétaro',
 'Saltillo',
 'San Luis Potosí',
 'Tepic',
 'Tlaxcala',
 'Toluca',
 'Tuxtla Gutiérrez',
 'Villahermosa',
 'Xalapa',
 'Zacatecas']

## Programación orientada a arrays

**¿Qué es un array?**

Un array (o arreglo) es una estructura de datos que sirve para guardar varios valores en una sola variable.
A diferencia de una variable común (que solo puede guardar un dato), un array puede guardar una colección de datos del mismo tipo, por ejemplo, varios números o varias palabras

Calificaciones de 5 alumnos.

In [ ]:
calif1 = 8.5
calif2 = 9.0
calif3 = 7.5
calif4 = 10.0
calif5 = 8.0


Sería más ordenado usar un solo contenedor que guarde todas las calificaciones:

In [ ]:
cal = [8.5, 9.0, 7.5, 10.0, 8.0]
cal

[8.5, 9.0, 7.5, 10.0, 8.0]

| Concepto      | Explicación                                                                   |
| ------------- | ----------------------------------------------------------------------------- |
| **Array**     | Es una colección de datos almacenados en una sola variable.                   |
| **Índice**    | Es la posición de cada elemento dentro del array (comienza en 0).             |



**Arrays como Vectores y Matrices**

In [ ]:
valores = [1, 2, 3, 4] #array de una sola fila o columna = Vector


Cuando usas NumPy:

En la librería NumPy, los arrays pueden tener una o más dimensiones.

In [ ]:
import numpy as np

# Array de una dimensión (vector)
a = np.array([1, 2, 3])

# Array de dos dimensiones (matriz)
b = np.array([[1, 2, 3],
              [4, 5, 6]])


In [ ]:
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

#Operaciones básicas

| Operación                          | Ejemplo  | Resultado                                          |
| ---------------------------------- | -------- | -------------------------------------------------- |
| Suma                               | `A + B`  | Suma elemento a elemento                           |
| Resta                              | `A - B`  | Resta elemento a elemento                          |
| Multiplicación elemento a elemento | `A * B`  | Cada elemento se multiplica con su correspondiente |
| División elemento a elemento       | `A / B`  | Cada elemento se divide entre su correspondiente   |
| Potencia                           | `A ** 2` | Eleva cada elemento al cuadrado                    |


#Operaciones algebraicas con NumPy

| **Operación**                                | **Símbolo / Función en NumPy** | **Ejemplo**                              | **Resultado / Descripción**                |
| -------------------------------------------- | ------------------------------ | ---------------------------------------- | ------------------------------------------ |
| **Transpuesta**                              | `A.T`                          | `A.T`                                    | Intercambia filas ↔ columnas               |
| **Inversa de matriz**                        | `np.linalg.inv(A)`             | Solo si A es cuadrada                    | Devuelve la matriz inversa                 |
| **Determinante**                             | `np.linalg.det(A)`             | `np.linalg.det(A)`                       | Devuelve un número                         |
| **Traza**                                    | `np.trace(A)`                  | `np.trace(A)`                            | Suma de los elementos de la diagonal       |
| **Producto escalar (entre vectores)**        | `np.dot(a, b)`                 | `np.dot([1,2,3], [4,5,6]) → 32`          | Resultado **numérico**                     |
| **Producto vectorial (entre vectores 3D)**   | `np.cross(a, b)`               | `np.cross([1,0,0], [0,1,0]) → [0,0,1]`   | Resultado **vector perpendicular**         |
| **Producto de matrices (entre matrices 2D)** | `A @ B` o `np.dot(A, B)`       | `A @ B`                                  | Resultado **matriz**                       |
| **Norma de un vector**                       | `np.linalg.norm(a)`            | `np.linalg.norm([3,4]) → 5.0`            | Magnitud del vector                        |
| **Autovalores y autovectores**               | `np.linalg.eig(A)`             | `(valores, vectores) = np.linalg.eig(A)` | Valores característicos y vectores propios |


np.dot() cambia su comportamiento según las dimensiones:

1D → producto escalar

2D → producto matricial

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b) #Aquí ambos son vectores 1D, así que NumPy hace un producto escalar (dot product)
            #Resultado: un número (1×4 + 2×5 + 3×6 = 32)


np.int64(32)

In [ ]:
A = np.array([
    [2, 4, 6],
    [4, 5, 7],
    [6, 7, 9]
])

B = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

In [ ]:
A, B

(array([[2, 4, 6],
        [4, 5, 7],
        [6, 7, 9]]),
 array([[1, 2, 3],
        [0, 1, 4],
        [5, 6, 0]]))

In [ ]:
producto= np.dot(A, B)
print(producto)

[[32 44 22]
 [39 55 32]
 [51 73 46]]


Suma/resta de matrices

In [ ]:
C = A + B
C

array([[ 3,  6,  9],
       [ 4,  6, 11],
       [11, 13,  9]])

In [ ]:
A.T

array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])

In [ ]:
np.array_equal(A, A.T) #Compara elemento por elemento Si todos los valores coinciden, devuelve True. #Si al menos uno es diferente, devuelve False.


True

# Determinante

In [ ]:
np.linalg.det(A)

np.float64(3.9999999999999867)

# Inversa de una matriz

$$ A * A^{ -1} = I$$

In [ ]:
B_i = np.linalg.inv(B) #Inversa de una matriz
B_i


array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [ ]:
np.dot(B, B_i).round()   #Redondear con .round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

| Operación           | Función      |
| ------------------- | ------------ |
| Promedio            | `np.mean(A)` |         
| Suma total          | `np.sum(A)`  |        
| Mínimo              | `np.min(A)`  |         
| Máximo              | `np.max(A)`  |         
| Desviación estándar | `np.std(A)`  |         
| Varianza            | `np.var(A)`  |         


In [ ]:
A=np.array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])
A

array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])

In [ ]:
np.mean(A)

np.float64(5.555555555555555)

### Funciones rápidas de array elemento a elemento

| Función                | Descripción                                      |
|------------------------|--------------------------------------------------|
| `np.abs(x)`            | Valor absoluto: $|x|$                          |
| `np.sqrt(x)`           | Raíz cuadrada                                   |
| `np.square(x)`         | Cuadrado: $x^2$                                |
| `np.exp(x)`            | Exponencial: $e^x$                             |
| `np.log(x)`            | Logaritmo natural: $\ln(x)$                    |
| `np.log10(x)`          | Logaritmo base 10                                |
| `np.log2(x)`           | Logaritmo base 2                                 |
| `np.sin(x)`            | Seno (radianes)                                  |
| `np.cos(x)`            | Coseno (radianes)                                |
| `np.tan(x)`            | Tangente (radianes)                              |
| `np.arcsin(x)`         | Arcoseno (radianes)                              |
| `np.arccos(x)`         | Arcocoseno (radianes)                            |
| `np.arctan(x)`         | Arcotangente (radianes)                          |
| `np.sinh(x)`           | Seno hiperbólico                                 |
| `np.cosh(x)`           | Coseno hiperbólico                               |
| `np.tanh(x)`           | Tangente hiperbólica                             |
| `np.exp2(x)`           | Potencia de 2: $2^x$                           |
| `np.expm1(x)`          | $e^x - 1$ con mayor precisión para $x \approx 0$ |
| `np.log1p(x)`          | $\ln(1 + x)$ con mayor precisión para $x \approx 0$ |
| `np.rint(x)`           | Redondea al entero más cercano                   |
| `np.floor(x)`          | Parte entera hacia abajo                         |
| `np.ceil(x)`           | Parte entera hacia arriba                        |
| `np.trunc(x)`          | Parte entera eliminando decimales                |
| `np.sign(x)`           | Signo: -1, 0 o 1 según el signo de $x$         |
| `np.clip(x, a, b)`     | Limita valores de $x$ entre $a$ y $b$      |

Todas estas funciones se aplican **automáticamente elemento a elemento** sobre arrays, listas convertidas a arrays, o valores escalares.


In [ ]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

# Sistema de ecuaciones

Resuelve el siguiente sistema de ecuaciones aplicando el método de Cramer:

$$
\begin{cases}
2x_1 + 4x_2 + 6x_3 = 18, \\
4x_1 + 5x_2 + 6x_3 = 24, \\
3x_1 + x_2 - 2x_3 = 4.
\end{cases}
$$

1. Identifica la matriz de coeficientes (A)

In [ ]:
A = np.array([[2, 4, 6],
              [4, 5, 6],
              [3, 1, -2]])

2. Calcula el determinante principal (D o det(A))

In [ ]:
D=np.linalg.det(A)
D

np.float64(5.999999999999996)

3. Crea matrices modificadas para cada variable

- Para encontrar **X**: reemplaza la primera columna de A con el vector de términos independientes.
- Para encontrar **Y**: reemplaza la segunda columna
- Para encontrar **Z**: reemplaza la tercera columna (y así sucesivamente)

In [ ]:
X = np.array([[18,4,6],
               [24, 5,6],
               [4, 1, -2]])

4. Calcula el determinante de cada matriz modificada

Dx, Dy, Dz, etc.

In [ ]:
Dx = np.linalg.det(X)
Dx

np.float64(24.000000000000004)

5. Aplica la fórmula de Cramer

- x = Dx/D

- y = Dy/D

- z = Dz/D

In [ ]:
x = Dx/D
x

np.float64(4.0000000000000036)

In [ ]:
b = np.array([18,24,4])  #Comprobación

x=np.linalg.solve(A, b)
x

array([ 4., -2.,  3.])

In [ ]:
np.dot(A,x)


array([18., 24.,  4.])

# Ejercicio - Sistema 8x8
$$
x_1 + 2x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 = 16 \\
x_1 + x_2 + 2x_3 + x_4 + x_5 + x_6 + x_7 + x_8 = 15 \\
x_1 + x_2 + x_3 + 2x_4 + x_5 + x_6 + x_7 + x_8 = 14 \\
x_1 + x_2 + x_3 + x_4 + 2x_5 + x_6 + x_7 + x_8 = 13 \\
x_1 + x_2 + x_3 + x_4 + x_5 + 2x_6 + x_7 + x_8 = 12 \\
x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + 2x_7 + x_8 = 11 \\
x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + 2x_8 = 10 \\
2x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 = 17
$$

Matriz de coeficientes

In [ ]:
A = np.array([
    [1, 2, 1, 1, 1, 1, 1, 1],
    [1, 1, 2, 1, 1, 1, 1, 1],
    [1, 1, 1, 2, 1, 1, 1, 1],
    [1, 1, 1, 1, 2, 1, 1, 1],
    [1, 1, 1, 1, 1, 2, 1, 1],
    [1, 1, 1, 1, 1, 1, 2, 1],
    [1, 1, 1, 1, 1, 1, 1, 2],
    [2, 1, 1, 1, 1, 1, 1, 1]
], dtype=float)

Vector de términos independientes

In [ ]:
b = np.array([16, 15, 14, 13, 12, 11, 10, 17], dtype=float)

In [ ]:
x=np.linalg.solve(A, b)
x

array([ 5.00000000e+00,  4.00000000e+00,  3.00000000e+00,  2.00000000e+00,
        1.00000000e+00, -7.13714802e-17, -1.00000000e+00, -2.00000000e+00])

x₁ = 9, x₂ = 8, x₃ = 7, x₄ = 6, x₅ = 5, x₆ = 4, x₇ = 3, x₈ = 2

In [ ]:
np.dot(A,x)

array([16., 15., 14., 13., 12., 11., 10., 17.])

#Números aleatorios

La función randrange(a, b, salto) genera números enteros aleatorios comprendidos entre a y b separados entre sí con un salto.

Los números aleatorios no lo son realmente (son más bien pseudoaleatorios); en realidad los produce un generador de números aleatorios configurable, que determina de forma preestablecida qué valores se crean.

In [ ]:
rng = np.random.default_rng(seed=123) #El argumento seed determina
                                    #el estado inicial del generador
arr = rng.standard_normal((5, 4))

In [ ]:
arr

array([[-0.98912135, -0.36778665,  1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379, -0.63646365,  0.54195222],
       [-0.31659545, -0.32238912,  0.09716732, -1.52593041],
       [ 1.1921661 , -0.67108968,  1.00026942,  0.13632112],
       [ 1.53203308, -0.65996941, -0.31179486,  0.33776913]])

In [ ]:
import random as rd

In [ ]:
for i in range(8):
    print(rd.randrange(5, 200, 2))

163
13
93
79
165
41
61
87


In [ ]:
 # random() devuelve un float comprendido entre [0,1)

for i in range(11):
    print(rd.random())

0.4365001832505503
0.27901352731297957
0.5820173114472638
0.104108848649907
0.9642857537752918
0.7582622964715662
0.2275170627962566
0.4673496085368505
0.25256392202004474
0.021097296262157283
0.6446146255964919


choice() devuelve un elemento aleatorio de una lista.

In [ ]:
frutas = ['peras', 'manzanas', 'plátanos', 'ciruelas','mangos']

for i in range(8):
    print(rd.choice(frutas))

peras
manzanas
mangos
plátanos
manzanas
peras
ciruelas
peras


In [ ]:
rd.choice(frutas)

'mangos'

# **La función shuffle()**
 modifica el orden de los elementos de una lista. Esta función se asemeja a la acción de mezclar una baraja.

In [ ]:
baraja = list(range(1,13))

for i in range(5):
    rd.shuffle(baraja)
    print(baraja)

[2, 1, 8, 3, 6, 10, 12, 11, 7, 9, 5, 4]
[4, 12, 7, 6, 8, 10, 1, 3, 11, 5, 9, 2]
[11, 7, 9, 3, 10, 6, 12, 1, 4, 2, 8, 5]
[4, 3, 2, 8, 1, 6, 5, 10, 9, 12, 7, 11]
[5, 3, 7, 11, 12, 6, 8, 2, 1, 4, 9, 10]


El módulo numpy.random complementa el módulo random interno de Python con funciones para generar de forma eficaz arrays enteros de valores de muestra de muchos tipos de distribuciones de probabilidad.

In [ ]:
samples = np.random.standard_normal(size=(3, 3))
samples

array([[ 0.5334463 , -0.46579267, -0.45204875],
       [ 0.13014477,  1.02872721, -0.06401805],
       [-1.0967015 , -1.0352029 ,  0.15085764]])

| Distribución                | Función                                 | Firma básica                                         |
|-----------------------------|-----------------------------------------|------------------------------------------------------|
| Uniforme continua           | `np.random.uniform`                     | `(low=0.0, high=1.0, size=None)`                     |
| Normal (Gaussiana)          | `np.random.normal`                      | `(loc=0.0, scale=1.0, size=None)`                    |
| Lognormal                   | `np.random.lognormal`                   | `(mean=0.0, sigma=1.0, size=None)`                   |
| Exponencial                 | `np.random.exponential`                 | `(scale=1.0, size=None)`                             |
| Gamma                       | `np.random.gamma`                       | `(shape, scale=1.0, size=None)`                      |
| Beta                        | `np.random.beta`                        | `(a, b, size=None)`                                  |
| Chi-cuadrado                | `np.random.chisquare`                   | `(df, size=None)`                                    |
| Laplace (doble exponencial) | `np.random.laplace`                     | `(loc=0.0, scale=1.0, size=None)`                    |
| Logística                   | `np.random.logistic`                    | `(loc=0.0, scale=1.0, size=None)`                    |
| Gumbel (máximo)             | `np.random.gumbel`                      | `(loc=0.0, scale=1.0, size=None)`                    |
| Pareto                      | `np.random.pareto`                      | `(a, size=None)`                                     |
| Weibull                     | `np.random.weibull`                     | `(a, size=None)`                                     |
| Triangular                  | `np.random.triangular`                  | `(left, mode, right, size=None)`                     |
| Enteros uniformes           | `np.random.randint`                     | `(low, high=None, size=None)`                        |
| Binomial                    | `np.random.binomial`                    | `(n, p, size=None)`                                  |
| Poisson                     | `np.random.poisson`                     | `(lam=1.0, size=None)`                               |
| Geométrica                  | `np.random.geometric`                   | `(p, size=None)`                                     |
| Hipergeométrica             | `np.random.hypergeometric`              | `(ngood, nbad, nsample, size=None)`                  |
| Multinomial                 | `np.random.multinomial`                 | `(n, pvals, size=None)`                              |
| Binomial negativa           | `np.random.negative_binomial`           | `(n, p, size=None)`                                  |
| Elección de elementos       | `np.random.choice`                      | `(a, size=None, replace=True, p=None)`               |
| Barajar (lista / arreglo)   | `np.random.shuffle`                     | `(x)` (modifica x in-place)                          |
| Cauchy estándar             | `np.random.standard_cauchy`             | `(size=None)`                                        |


Genera un arreglo con las edades de 200 personas adultas de entre 18 y 65 años. Responde lo siguiente:

¿Cuáles son los valores únicos de edad y su frecuencia?

¿Cuál es la edad más común y cuántas veces aparece?.

¿Cuántas personas tienen más de 30 años?

In [ ]:
edades = np.random.randint(18, 66, size=200)
edades

array([22, 48, 62, 51, 48, 41, 37, 28, 54, 33, 45, 41, 37, 28, 40, 62, 64,
       44, 64, 48, 50, 27, 18, 64, 40, 36, 34, 51, 39, 22, 40, 34, 48, 61,
       29, 62, 27, 57, 38, 41, 24, 31, 47, 37, 21, 35, 57, 26, 18, 27, 57,
       52, 32, 20, 41, 33, 41, 33, 43, 44, 24, 49, 47, 32, 21, 51, 49, 49,
       31, 19, 33, 31, 49, 51, 58, 20, 30, 25, 36, 26, 63, 61, 49, 59, 24,
       35, 37, 42, 30, 29, 41, 21, 26, 20, 41, 35, 44, 62, 63, 37, 58, 20,
       19, 22, 20, 37, 62, 27, 24, 32, 22, 47, 44, 47, 31, 55, 38, 57, 29,
       50, 32, 57, 36, 40, 26, 50, 18, 50, 46, 24, 44, 61, 29, 47, 53, 48,
       49, 27, 41, 45, 42, 39, 31, 51, 18, 25, 39, 24, 64, 23, 22, 61, 52,
       47, 39, 48, 26, 48, 52, 61, 63, 28, 54, 40, 29, 19, 45, 63, 52, 26,
       40, 54, 50, 36, 51, 44, 41, 28, 34, 27, 38, 50, 18, 40, 39, 65, 20,
       63, 25, 31, 44, 54, 64, 49, 33, 20, 38, 56, 18, 45])